### ISSUE TITLE
Upload specification table to Google spreadsheet

### ISSUE THREAD

**Issue by shohei** [nakujaproject/N2-development#21]
@dmashy Please upload the specification table on Google spreadsheet!

**Comment by dmashy** [comment]
kindly find attached google sheet link
https://docs.google.com/spreadsheets/d/1VhsNEhUsmTSWweohD7DSBD2Lo-8im8xtNGFmmfiWn94/edit?usp=sharing

**Comment by shohei** [comment]
@dmashy Thank you Destine!
