### ISSUE TITLE
Gantt chart for airframe team

### ISSUE THREAD

**Issue by shohei** [nakujaproject/N2-development#9]

**Comment by dmashy** [comment]
Gantt Chart Link
https://docs.google.com/spreadsheets/d/1YrMPQ5__zrfVqBihiMABT6rJ27Gi4PSsSB8DGsg3uyg/edit?usp=sharing

**Comment by dmashy** [comment]
Find attached Gantt chart

[AIRFRAME GANTT CHART.pptx](https://github.com/nakujaproject/N2-development/files/7468382/AIRFRAME.GANTT.CHART.pptx)

**Comment by shohei** [comment]
@dmashy Thanks for sharing!
